apiVersion: abtesting.com/v1
kind: ABTest
metadata:
  labels:
    app.kubernetes.io/name: ab-testing-operator
    app.kubernetes.io/managed-by: kustomize
  name: myapp-deployment-abtest
spec:
  enabled: true
  targetService: myapp-deployment
  image: nginx:latest
  port: 80
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
