apiVersion: abtesting.com/v1
kind: ABTest
metadata:
  labels:
    app.kubernetes.io/name: ab-testing-operator
    app.kubernetes.io/managed-by: kustomize
  name: wallet-service
spec:
  targetService: wallet-service
  trafficWeight: 50
  image: nginx:perl
  replicas: 2
  port: 80
