apiVersion: abtesting.com/v1
kind: ABTest
metadata:
  labels:
    app.kubernetes.io/name: ab-testing-operator
    app.kubernetes.io/managed-by: kustomize
  name: myapp-deployment-abtest
spec:
  targetService: myapp-deployment
  trafficWeight: 50
  image: promhippie/dockerhub_exporter
  replicas: 2
  port: 9505